controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

inicio:
    path: /
    controller: App\Controller\SplashController::index

app_training:
    path: /formacion
    controller: App\Controller\TrainingController::index

app_work_experience:
    path: /experiencia
    controller: App\Controller\WorkExperienceController::index